# Generated by Django 6.0.2 on 2026-02-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_alter_equipment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
