# Generated by Django 6.0.2 on 2026-04-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_groups'),
        ('equipment', '0002_equipment_data'),
        ('exercise', '0002_exercise_data'),
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourite_equipments',
            field=models.ManyToManyField(blank=True, related_name='user_favourite', to='equipment.equipment'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favourite_exercises',
            field=models.ManyToManyField(blank=True, related_name='user_favourite', to='exercise.exercise'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favourite_workoutplans',
            field=models.ManyToManyField(blank=True, related_name='user_favourite', to='workout.workoutplan'),
        ),
    ]
