# Generated by Django 6.0.2 on 2026-03-15 15:53

import common.validators
import django.db.models.deletion
import workout.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercise', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, validators=[common.validators.validate_alphanumeric_spaces])),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('private', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_plan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(validators=[workout.validators.min_value_validator])),
                ('sets', models.PositiveIntegerField(validators=[workout.validators.min_value_validator])),
                ('reps', models.PositiveIntegerField(blank=True, null=True, validators=[workout.validators.min_value_validator])),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, validators=[workout.validators.min_value_validator])),
                ('rest_seconds', models.PositiveIntegerField(default=60, validators=[workout.validators.min_value_validator])),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workout.workoutplan')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('workout', 'exercise')},
            },
        ),
    ]
