# Generated by Django 6.0.2 on 2026-02-14 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutplan',
            name='difficulty',
        ),
    ]
