# Generated by Django 6.0.2 on 2026-03-14 13:28

import workout.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutexercise',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[workout.validators.min_value_validator]),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='order',
            field=models.PositiveIntegerField(validators=[workout.validators.min_value_validator]),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='reps',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[workout.validators.min_value_validator]),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='rest_seconds',
            field=models.PositiveIntegerField(default=60, validators=[workout.validators.min_value_validator]),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='sets',
            field=models.PositiveIntegerField(validators=[workout.validators.min_value_validator]),
        ),
    ]
