# Generated by Django 6.0.2 on 2026-02-15 11:55

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_remove_workoutplan_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutplan',
            name='name',
            field=models.CharField(max_length=100, validators=[common.validators.validate_alphanumeric_spaces]),
        ),
    ]
