# Generated by Django 6.0.2 on 2026-02-15 15:54

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_alter_workoutplan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutplan',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[common.validators.validate_alphanumeric_spaces]),
        ),
    ]
