# Generated by Django 6.0.2 on 2026-03-15 15:53

import common.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, validators=[common.validators.validate_alphanumeric_spaces])),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('primary_muscle_group', models.CharField(choices=[('Chest', 'Chest'), ('Back', 'Back'), ('Legs', 'Legs'), ('Shoulders', 'Shoulders'), ('Arms', 'Arms'), ('Core', 'Core')], max_length=50)),
                ('secondary_muscle_group', models.CharField(blank=True, choices=[('Chest', 'Chest'), ('Back', 'Back'), ('Legs', 'Legs'), ('Shoulders', 'Shoulders'), ('Arms', 'Arms'), ('Core', 'Core')], max_length=50, null=True)),
                ('is_bodyweight', models.BooleanField(default=False)),
                ('private', models.BooleanField(default=False)),
                ('system_generated', models.BooleanField(default=False)),
                ('equipment', models.ManyToManyField(blank=True, related_name='exercises', to='equipment.equipment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
