# Generated by Django 6.0.2 on 2026-02-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_exercise_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='secondary_muscle_group',
            field=models.CharField(blank=True, choices=[('Chest', 'Chest'), ('Back', 'Back'), ('Legs', 'Legs'), ('Shoulders', 'Shoulders'), ('Arms', 'Arms'), ('Core', 'Core')], max_length=50, null=True),
        ),
    ]
