# Generated by Django 6.0.2 on 2026-02-15 11:55

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_exercise_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[common.validators.validate_alphanumeric_spaces]),
        ),
    ]
